### ISSUE TITLE
Update Python wrapping

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#53]
I ran into: `itkOMEZarrNGFFImageIO: warning(4): ITK type not wrapped, or currently not known: itk::OMEZarrNGFFAxis`

**Comment by dzenanz** [comment]
Tom, can you confirm/fix this?

**Comment by tbirdso** [comment]
Interesting, I do not see the warning message in Python 3.8:
```py
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import itk
>>> itk.auto_progress(2)
>>> itk.OMEZarrNGFFImageIO.New()
Loading ITKPyBase... done
Loading ITKCommon... done
Loading ITKIOImageBase... Loading ITKIOHDF5... done
Loading IOOMEZarrNGFF... done
Loading ITKIOBMP... done
Loading ITKIOBioRad... done
Loading ITKIOBruker... done
Loading ITKIOGDCM... done
Loading ITKIOIPL... done
Loading ITKIOGE... done
Loading ITKIOGIPL... done
Loading ITKIOJPEG... done
Loading ITKIOJPEG2000... done
Loading ITKIOTIFF... done
Loading ITKIOLSM... done
Loading ITKIOMINC... done
Loading ITKIOMRC... done
Loading ITKIOMeta... done
Loading ITKStatistics... done
Loading ITKImageFilterBase... done
Loading ITKTransform... done
Loading ITKIONIFTI... done
Loading ITKIONRRD... done
Loading ITKIOPNG... done
Loading ITKIOStimulate... done
Loading ITKIOVTK... done
done
Loading ITKPyUtils... done
<itk.itkOMEZarrNGFFImageIOPython.itkOMEZarrNGFFImageIO; proxy of <Swig Object of type 'itkOMEZarrNGFFImageIO *' at 0x000001CB2CBA38A0> >
```

But I agree that `itk.OMEZarrNGFFAxis` is not yet wrapped and it would not take much effort to do so:
```py
>>> itk.OMEZarrNGFFAxis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\itk\support\lazy.py", line 131, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'OMEZarrNGFFAxis'
```
